[package]
name = "filecoin-webapi"
version = "0.1.0"
authors = ["石博文 <sbw@sbw.so>"]
edition = "2018"

[profile.release]
lto = true

[lib]
crate-type = ["rlib"]
name = "filecoin_webapi"
path = "src/lib.rs"
edition = "2018"

[[bin]]
name = "filecoin-webapi"
path = "src/main.rs"

[dependencies]
actix-rt = "*"
actix-web = { version = "^3", features = ["openssl"] }
actix-multipart = "*"
futures = "*"
futures-core = "*"
futures-util = "*"
log = "*"
env_logger = "*"
clap = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
serde_yaml = "*"
mime = "*"
lazy_static = "*"
libc = "*"
bytes = "~0.5"
#bellperson = { version = "0.12", default-features = false }
bellperson = { path = "../bellperson", default-features = false }
openssl = "*"
std-semaphore = "0.1"

[dependencies.filecoin-proofs-api]
package = "filecoin-proofs-api"
version = "5.4.1"
path = "../rust-filecoin-proofs-api/"
default-features = false

[features]
default = ["pairing"]
pairing = ["filecoin-proofs-api/pairing", "bellperson/pairing"]
blst = ["filecoin-proofs-api/blst", "bellperson/blst"]

[patch.crates-io]
bellperson = { git = "https://github.com/sbwtw/bellperson", branch = "3080" }
